spring:
  mail: # <-- Uncommented
    host: smtp.gmail.com # Make sure these values are correct for your provider
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      # mail.smtp.starttls.required: true # Often optional, depends on provider
  logging:
    level:
      com.zaxxer.hikari: DEBUG
      br.com.brittosw.stockmanagement.config: DEBUG
      org.hibernate.SQL: DEBUG

  datasource:
    url: 'jdbc:postgresql://stockmanagement.cd0q6ysw8z6g.us-east-2.rds.amazonaws.com:5432/postgres'
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  task:
    scheduling:
      pool:
        size: 5
  config:
    import: "zookeeper:"
  cloud:
    zookeeper:
      connect-string: localhost:2181
      config:
        enabled: true
        root: /configuration

  whatsapp:
    api:
      url: 'https://graph.facebook.com/v22.0/662847286904556/messages'
  notification:
    whatsapp:
      enabled: true
